"""market API — auto-generated from OpenAPI spec."""

from lolzpy.market._client import (  # noqa: F401
    AsyncAutoPayments,
    AsyncBatch,
    AsyncCart,
    AsyncCategory,
    AsyncCustomDiscounts,
    AsyncImap,
    AsyncList,
    AsyncManaging,
    AsyncPayments,
    AsyncProfile,
    AsyncProxy,
    AsyncPublishing,
    AsyncPurchasing,
    SyncAutoPayments,
    SyncBatch,
    SyncCart,
    SyncCategory,
    SyncCustomDiscounts,
    SyncImap,
    SyncList,
    SyncManaging,
    SyncPayments,
    SyncProfile,
    SyncProxy,
    SyncPublishing,
    SyncPurchasing,
)
