# generated by datamodel-codegen:
#   filename:  forum.json

from __future__ import annotations

from enum import IntEnum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class UserIDModel(RootModel[str | int]):
    root: Annotated[str | int, Field(title="user_id")]


class Links(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    content: Annotated[str, Field(title="Content")]
    creator_avatar: Annotated[str, Field(title="Creator")]


class RespNotificationModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    notification_id: Annotated[int, Field(title="Notification")]
    notification_create_date: Annotated[int, Field(title="Notification")]
    content_type: Annotated[str, Field(title="Content")]
    content_id: Annotated[int, Field(title="Content")]
    content_action: Annotated[str, Field(title="Content")]
    notification_is_unread: Annotated[bool, Field(title="Notification")]
    creator_user_id: Annotated[int, Field(title="Creator")]
    creator_username: Annotated[str, Field(title="Creator")]
    creator_username_html: Annotated[str, Field(title="Creator")]
    notification_type: Annotated[str, Field(title="Notification")]
    links: Annotated[Links, Field(title="Links")]
    notification_html: Annotated[str, Field(title="Notification")]


class Links1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    target: Annotated[str, Field(title="Target")]
    detail: Annotated[str, Field(title="Detail")]


class Permissions(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    view: Annotated[bool, Field(title="View")]


class RespLinkModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    link_id: Annotated[int, Field(title="Link")]
    link_title: Annotated[str, Field(title="Link")]
    link_description: Annotated[str, Field(title="Link")]
    links: Annotated[Links1, Field(title="Links")]
    permissions: Annotated[Permissions, Field(title="Permissions")]


class RoomIDModel(IntEnum):
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4
    integer_13 = 13


class Room(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    can_report: Annotated[bool, Field(title="Can")]
    eng: Annotated[bool, Field(title="Eng")]
    market: Annotated[bool, Field(title="Market")]
    room_id: Annotated[int, Field(title="Room")]
    title: Annotated[str, Field(title="Title")]


class Avatars(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    l: Annotated[str, Field(title="L")]
    m: Annotated[str, Field(title="M")]
    s: Annotated[str, Field(title="S")]


class Rendered(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    username: Annotated[str, Field(title="Username")]
    avatars: Annotated[Avatars, Field(title="Avatars")]
    link: Annotated[str, Field(title="Link")]


class UniqBanner(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    banner_css: Annotated[str, Field(title="Banner")]
    banner_text: Annotated[str, Field(title="Banner")]
    banner_icon: Annotated[str, Field(title="Banner")]
    username_icon: Annotated[str, Field(title="Username")]


class User(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    avatar_date: Annotated[int, Field(title="Avatar")]
    background_date: Annotated[int, Field(title="Background")]
    contest_count: Annotated[int, Field(title="Contest")]
    custom_title: Annotated[str, Field(title="Custom")]
    display_banner_id: Annotated[int, Field(title="Display")]
    display_icon_group_id: Annotated[int, Field(title="Display")]
    display_style_group_id: Annotated[int, Field(title="Display")]
    is_admin: Annotated[bool, Field(title="Is")]
    is_banned: Annotated[bool, Field(title="Is")]
    is_moderator: Annotated[bool, Field(title="Is")]
    is_staff: Annotated[bool, Field(title="Is")]
    last_activity: Annotated[int, Field(title="Last")]
    like2_count: Annotated[int, Field(title="Like")]
    like_count: Annotated[int, Field(title="Like")]
    message_count: Annotated[int, Field(title="Message")]
    register_date: Annotated[int, Field(title="Register")]
    rendered: Annotated[Rendered, Field(title="Rendered")]
    short_link: Annotated[str, Field(title="Short")]
    trophy_points: Annotated[int, Field(title="Trophy")]
    uniq_banner: Annotated[UniqBanner, Field(title="Uniq")]
    uniq_username_css: Annotated[str, Field(title="Uniq")]
    user_id: Annotated[int, Field(title="User")]
    username: Annotated[str, Field(title="Username")]


class RespChatboxMessageModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    can_report: Annotated[bool, Field(title="Can")]
    date: Annotated[int, Field(title="Date")]
    is_deleted: Annotated[bool, Field(title="Is")]
    message: Annotated[str, Field(title="Message")]
    message_id: Annotated[int, Field(title="Message")]
    message_json: Annotated[str, Field(alias="messageJson", title="Message Json")]
    message_raw: Annotated[str, Field(alias="messageRaw", title="Message Raw")]
    room: Annotated[Room, Field(title="Room")]
    user: Annotated[User, Field(title="User")]


class Links2(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    permalink: Annotated[str, Field(title="Permalink")]
    detail: Annotated[str, Field(title="Detail")]
    avatar: Annotated[str, Field(title="Avatar")]
    avatar_big: Annotated[str, Field(title="Avatar")]
    avatar_small: Annotated[str, Field(title="Avatar")]
    followers: Annotated[str, Field(title="Followers")]
    followings: Annotated[str, Field(title="Followings")]
    ignore: Annotated[str, Field(title="Ignore")]
    background_l: Annotated[str, Field(title="Background Large")]
    background_m: Annotated[str, Field(title="Background Medium")]
    status: Annotated[str, Field(title="Status")]
    timeline: Annotated[str, Field(title="Timeline")]


class Permissions1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    edit: Annotated[bool, Field(title="Edit")]
    follow: Annotated[bool, Field(title="Follow")]
    ignore: Annotated[bool, Field(title="Ignore")]
    profile_post: Annotated[bool, Field(title="Profile")]


class UserGroup(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    user_group_id: Annotated[int, Field(title="User")]
    user_group_title: Annotated[str, Field(title="User")]
    user_group_title_en: Annotated[str, Field(title="User")]
    user_group_banner_css_class: Annotated[str, Field(title="User")]
    user_group_banner_text: Annotated[str, Field(title="User")]
    user_group_banner_text_en: Annotated[str, Field(title="User")]
    display_group_selectable: Annotated[bool, Field(title="Display")]
    display_banner_selectable: Annotated[bool, Field(title="Display")]
    display_icon_selectable: Annotated[bool, Field(title="Display")]
    is_primary_group: Annotated[bool, Field(title="Is")]
    user_group_icon_class: Annotated[str, Field(title="User")]


class Choice(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    key: Annotated[str, Field(title="Key")]
    value: Annotated[str, Field(title="Value")]


class FieldModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Annotated[str, Field(title="Id")]
    title: Annotated[str, Field(title="Title")]
    description: Annotated[str, Field(title="Description")]
    position: Annotated[str, Field(title="Position")]
    is_required: Annotated[bool, Field(title="Is")]
    value: Annotated[str | None, Field(title="Value")] = None
    is_multi_choice: Annotated[bool, Field(title="Is")]
    choices: Annotated[list[Choice], Field(title="Choices")]
    values: Annotated[list[Any], Field(title="Values")]


class UserExternalAuthentication(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    provider: Annotated[str, Field(title="Provider")]
    provider_key: Annotated[str, Field(title="Provider")]


class SelfPermissions(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    create_conversation: Annotated[bool, Field(title="Create")]


class EditPermissions(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    password: Annotated[bool, Field(title="Password")]
    user_email: Annotated[bool, Field(title="User")]
    username: Annotated[bool, Field(title="Username")]
    user_title: Annotated[bool, Field(title="User")]
    short_link: Annotated[bool, Field(title="Short")]
    hide_username_logs: Annotated[bool, Field(title="Hide")]
    primary_group_id: Annotated[bool, Field(title="Primary")]
    secondary_group_ids: Annotated[bool, Field(title="Secondary")]
    user_dob_day: Annotated[bool, Field(title="User")]
    user_dob_month: Annotated[bool, Field(title="User")]
    user_dob_year: Annotated[bool, Field(title="User")]
    fields: Annotated[bool, Field(title="Fields")]


class TimeStamp(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    date: Annotated[str, Field(title="Date")]
    timezone_type: Annotated[int, Field(title="Timezone")]
    timezone: Annotated[str, Field(title="Timezone")]


class Birthday(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    age: Annotated[int, Field(title="Age")]
    time_stamp: Annotated[TimeStamp, Field(alias="timeStamp", title="Time Stamp")]
    format: Annotated[str, Field(title="Format")]


class User1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    user_id: Annotated[int, Field(title="User")]
    username: Annotated[str, Field(title="Username")]
    username_html: Annotated[str, Field(title="Username")]
    avatar: Annotated[str, Field(title="Avatar")]


class UserFollowing(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    users: Annotated[list[User1], Field(title="Users")]
    count: Annotated[int, Field(title="Count")]


class UserFollowers(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    users: Annotated[list[User1], Field(title="Users")]
    count: Annotated[int, Field(title="Count")]


class RespUserModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    user_id: Annotated[int, Field(title="User")]
    username: Annotated[str, Field(title="Username")]
    username_html: Annotated[str, Field(title="Username")]
    user_message_count: Annotated[int, Field(title="User")]
    user_register_date: Annotated[int, Field(title="User")]
    user_like_count: Annotated[int, Field(title="User")]
    user_like2_count: Annotated[int, Field(title="User")]
    contest_count: Annotated[int, Field(title="Contest")]
    trophy_count: Annotated[int, Field(title="Trophy")]
    short_link: Annotated[str, Field(title="Short")]
    custom_title: Annotated[str, Field(title="Custom")]
    is_banned: Annotated[int, Field(title="Is")]
    display_banner_id: Annotated[int, Field(title="Display")]
    display_icon_group_id: Annotated[int, Field(title="Display")]
    balance: Annotated[str, Field(title="Balance")]
    hold: Annotated[str, Field(title="Hold")]
    currency: Annotated[str, Field(title="Currency")]
    user_email: Annotated[str, Field(title="User")]
    user_unread_notification_count: Annotated[int, Field(title="User")]
    user_unread_conversation_count: Annotated[int, Field(title="User")]
    conv_welcome_message: Annotated[str, Field(title="Conv")]
    user_title: Annotated[str, Field(title="User")]
    user_deposit: Annotated[int, Field(title="User")]
    user_is_valid: Annotated[bool, Field(title="User")]
    user_is_verified: Annotated[bool, Field(title="User")]
    user_is_followed: Annotated[bool, Field(title="User")]
    user_last_seen_date: Annotated[int, Field(title="User")]
    links: Annotated[Links2, Field(title="Links")]
    permissions: Annotated[Permissions1, Field(title="Permissions")]
    user_is_ignored: Annotated[bool, Field(title="User")]
    user_is_visitor: Annotated[bool, Field(title="User")]
    user_group_id: Annotated[int, Field(title="User")]
    curator_titles: Annotated[list[str], Field(title="Curator")]
    user_groups: Annotated[list[UserGroup], Field(title="User")]
    fields: Annotated[list[FieldModel], Field(title="Fields")]
    user_timezone_offset: Annotated[int, Field(title="User")]
    user_external_authentications: Annotated[list[UserExternalAuthentication], Field(title="User")]
    self_permissions: Annotated[SelfPermissions, Field(title="Self")]
    edit_permissions: Annotated[EditPermissions, Field(title="Edit")]
    birthday: Annotated[Birthday, Field(title="Birthday")]
    secret_answer_rendered: Annotated[str, Field(title="Secret")]
    secret_answer_first_letter: Annotated[str, Field(title="Secret")]
    user_following: Annotated[UserFollowing, Field(title="User")]
    user_followers: Annotated[UserFollowers, Field(title="User")]
    banner: Annotated[str, Field(title="Banner")]


class Links3(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    permalink: Annotated[str, Field(title="Permalink")]
    detail: Annotated[str, Field(title="Detail")]
    thread: Annotated[str, Field(title="Thread")]
    poster: Annotated[str, Field(title="Poster")]
    likes: Annotated[str, Field(title="Likes")]
    report: Annotated[str, Field(title="Report")]
    poster_avatar: Annotated[str, Field(title="Poster")]


class Permissions2(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    view: Annotated[bool, Field(title="View")]
    edit: Annotated[bool, Field(title="Edit")]
    delete: Annotated[bool, Field(title="Delete")]
    reply: Annotated[bool, Field(title="Reply")]
    like: Annotated[bool, Field(title="Like")]
    report: Annotated[bool, Field(title="Report")]


class FirstPost(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    post_id: Annotated[int, Field(title="Post")]
    thread_id: Annotated[int, Field(title="Thread")]
    poster_user_id: Annotated[int, Field(title="Poster")]
    poster_username: Annotated[str, Field(title="Poster")]
    poster_username_html: Annotated[str, Field(title="Poster")]
    post_create_date: Annotated[int, Field(title="Post")]
    post_body: Annotated[str, Field(title="Post")]
    post_body_html: Annotated[str, Field(title="Post")]
    post_body_plain_text: Annotated[str, Field(title="Post")]
    signature: Annotated[str, Field(title="Signature")]
    signature_html: Annotated[str, Field(title="Signature")]
    signature_plain_text: Annotated[str, Field(title="Signature")]
    post_like_count: Annotated[int, Field(title="Post")]
    user_is_ignored: Annotated[bool, Field(title="User")]
    post_is_published: Annotated[bool, Field(title="Post")]
    post_is_deleted: Annotated[bool, Field(title="Post")]
    post_update_date: Annotated[int, Field(title="Post")]
    post_is_first_post: Annotated[bool, Field(title="Post")]
    post_is_liked: Annotated[bool, Field(title="Post")]
    links: Annotated[Links3, Field(title="Links")]
    permissions: Annotated[Permissions2, Field(title="Permissions")]
    thread_is_deleted: Annotated[bool, Field(title="Thread")]


class ThreadTags(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_97491: Annotated[str, Field(alias="97491", title="")]
    field_193431: Annotated[str, Field(alias="193431", title="")]
    field_206: Annotated[str, Field(alias="206", title="")]


class Links4(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    permalink: Annotated[str, Field(title="Permalink")]
    detail: Annotated[str, Field(title="Detail")]
    followers: Annotated[str, Field(title="Followers")]
    forum: Annotated[str, Field(title="Forum")]
    posts: Annotated[str, Field(title="Posts")]
    first_poster: Annotated[str, Field(title="First")]
    first_poster_avatar: Annotated[str, Field(title="First")]
    first_post: Annotated[str, Field(title="First")]
    last_post: Annotated[str, Field(title="Last")]


class Bump(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    can: Annotated[bool, Field(title="Can")]
    available_count: Annotated[int, Field(title="Available")]
    error: Annotated[Any, Field(title="Error")]
    next_available_time: Annotated[Any, Field(title="Next")]


class Permissions3(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    view: Annotated[bool, Field(title="View")]
    delete: Annotated[bool, Field(title="Delete")]
    follow: Annotated[bool, Field(title="Follow")]
    post: Annotated[bool, Field(title="Post")]
    edit: Annotated[bool, Field(title="Edit")]
    edit_title: Annotated[bool, Field(title="Edit")]
    edit_tags: Annotated[bool, Field(title="Edit")]
    bump: Annotated[Bump, Field(title="Bump")]


class Restrictions(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    reply_delay: Annotated[int, Field(title="Reply")]
    max_reply_count: Annotated[int, Field(title="Max")]


class Links5(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    permalink: Annotated[str, Field(title="Permalink")]
    detail: Annotated[str, Field(title="Detail")]
    thread: Annotated[str, Field(title="Thread")]
    poster: Annotated[str, Field(title="Poster")]
    likes: Annotated[str, Field(title="Likes")]
    report: Annotated[str, Field(title="Report")]
    poster_avatar: Annotated[str, Field(title="Poster")]


class Permissions4(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    view: Annotated[bool, Field(title="View")]
    edit: Annotated[bool, Field(title="Edit")]
    delete: Annotated[bool, Field(title="Delete")]
    reply: Annotated[bool, Field(title="Reply")]
    like: Annotated[bool, Field(title="Like")]
    report: Annotated[bool, Field(title="Report")]


class LastPost(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    post_id: Annotated[int, Field(title="Post")]
    thread_id: Annotated[int, Field(title="Thread")]
    poster_user_id: Annotated[int, Field(title="Poster")]
    poster_username: Annotated[str, Field(title="Poster")]
    poster_username_html: Annotated[str, Field(title="Poster")]
    post_create_date: Annotated[int, Field(title="Post")]
    post_body: Annotated[str, Field(title="Post")]
    post_body_html: Annotated[str, Field(title="Post")]
    post_body_plain_text: Annotated[str, Field(title="Post")]
    signature: Annotated[str, Field(title="Signature")]
    signature_html: Annotated[str, Field(title="Signature")]
    signature_plain_text: Annotated[str, Field(title="Signature")]
    post_like_count: Annotated[int, Field(title="Post")]
    user_is_ignored: Annotated[bool, Field(title="User")]
    post_is_published: Annotated[bool, Field(title="Post")]
    post_is_deleted: Annotated[bool, Field(title="Post")]
    post_update_date: Annotated[int, Field(title="Post")]
    post_is_first_post: Annotated[bool, Field(title="Post")]
    post_is_liked: Annotated[bool, Field(title="Post")]
    links: Annotated[Links5, Field(title="Links")]
    permissions: Annotated[Permissions4, Field(title="Permissions")]
    thread_is_deleted: Annotated[bool, Field(title="Thread")]


class Permissions5(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    can_finish: Annotated[bool, Field(title="Can")]
    can_participate: Annotated[bool, Field(title="Can")]
    can_participate_error: Annotated[str, Field(title="Can")]
    can_view_user_list: Annotated[bool, Field(title="Can")]


class Contest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Annotated[str, Field(title="Type")]
    finish_date: Annotated[int, Field(title="Finish")]
    now_count_members: Annotated[int, Field(title="Now")]
    needed_members: Annotated[int, Field(title="Needed")]
    is_finished: Annotated[int, Field(title="Is")]
    count_winners: Annotated[int, Field(title="Count")]
    require_like_count: Annotated[int, Field(title="Require")]
    require_total_like_count: Annotated[int, Field(title="Require")]
    prize_type: Annotated[str, Field(title="Prize")]
    prize_type_phrase: Annotated[str, Field(title="Prize")]
    prize_data: Annotated[int, Field(title="Prize")]
    is_money_places: Annotated[int, Field(title="Is")]
    chance_to_win: Annotated[float, Field(title="Chance")]
    winners: Annotated[list[int], Field(title="Winners")]
    already_participate: Annotated[bool, Field(title="Already")]
    permissions: Annotated[Permissions5, Field(title="Permissions")]


class RespThreadModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    thread_id: Annotated[int, Field(title="Thread")]
    forum_id: Annotated[int, Field(title="Forum")]
    thread_title: Annotated[str, Field(title="Thread")]
    thread_view_count: Annotated[int, Field(title="Thread")]
    creator_user_id: Annotated[int, Field(title="Creator")]
    creator_username: Annotated[str, Field(title="Creator")]
    creator_username_html: Annotated[str, Field(title="Creator")]
    thread_create_date: Annotated[int, Field(title="Thread")]
    thread_update_date: Annotated[int, Field(title="Thread")]
    user_is_ignored: Annotated[bool, Field(title="User")]
    thread_post_count: Annotated[int, Field(title="Thread")]
    thread_is_published: Annotated[bool, Field(title="Thread")]
    thread_is_deleted: Annotated[bool, Field(title="Thread")]
    thread_is_sticky: Annotated[bool, Field(title="Thread")]
    thread_is_closed: Annotated[bool, Field(title="Thread")]
    thread_is_followed: Annotated[bool, Field(title="Thread")]
    thread_is_starred: Annotated[bool, Field(title="Thread")]
    first_post: Annotated[FirstPost, Field(title="First")]
    thread_prefixes: Annotated[list[Any], Field(title="Thread")]
    thread_tags: Annotated[ThreadTags, Field(title="Thread")]
    links: Annotated[Links4, Field(title="Links")]
    permissions: Annotated[Permissions3, Field(title="Permissions")]
    node_title: Annotated[str, Field(title="Node")]
    restrictions: Annotated[Restrictions, Field(title="Restrictions")]
    last_post: Annotated[LastPost, Field(title="Last")]
    contest: Contest


class Permissions6(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    view: Annotated[bool, Field(title="View")]
    edit: Annotated[bool, Field(title="Edit")]
    delete: Annotated[bool, Field(title="Delete")]
    reply: Annotated[bool, Field(title="Reply")]
    like: Annotated[bool, Field(title="Like")]
    report: Annotated[bool, Field(title="Report")]


class RespPostModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    post_id: Annotated[int, Field(title="Post")]
    thread_id: Annotated[int, Field(title="Thread")]
    poster_user_id: Annotated[int, Field(title="Poster")]
    poster_username: Annotated[str, Field(title="Poster")]
    poster_username_html: Annotated[str, Field(title="Poster")]
    post_create_date: Annotated[int, Field(title="Post")]
    post_body: Annotated[str, Field(title="Post")]
    post_body_html: Annotated[str, Field(title="Post")]
    post_body_plain_text: Annotated[str, Field(title="Post")]
    signature: Annotated[str, Field(title="Signature")]
    signature_html: Annotated[str, Field(title="Signature")]
    signature_plain_text: Annotated[str, Field(title="Signature")]
    post_like_count: Annotated[int, Field(title="Post")]
    user_is_ignored: Annotated[bool, Field(title="User")]
    post_is_published: Annotated[bool, Field(title="Post")]
    post_is_deleted: Annotated[bool, Field(title="Post")]
    post_update_date: Annotated[int, Field(title="Post")]
    post_is_first_post: Annotated[bool, Field(title="Post")]
    links: Annotated[Links5, Field(title="Links")]
    permissions: Annotated[Permissions6, Field(title="Permissions")]
    thread_is_deleted: Annotated[bool, Field(title="Thread")]


class Links7(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    permalink: Annotated[str, Field(title="Permalink")]
    detail: Annotated[str, Field(title="Detail")]
    post: Annotated[str, Field(title="Post")]
    thread: Annotated[str, Field(title="Thread")]
    poster: Annotated[str, Field(title="Poster")]
    likes: Annotated[str, Field(title="Likes")]
    report: Annotated[str, Field(title="Report")]
    poster_avatar: Annotated[str, Field(title="Poster")]


class RespPostCommentModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    post_comment_id: Annotated[int, Field(title="Post")]
    post_id: Annotated[int, Field(title="Post")]
    thread_id: Annotated[int, Field(title="Thread")]
    poster_user_id: Annotated[int, Field(title="Poster")]
    poster_username: Annotated[str, Field(title="Poster")]
    poster_username_html: Annotated[str, Field(title="Poster")]
    post_comment_create_date: Annotated[int, Field(title="Post")]
    post_comment_body: Annotated[str, Field(title="Post")]
    post_comment_body_html: Annotated[str, Field(title="Post")]
    post_comment_body_plain_text: Annotated[str, Field(title="Post")]
    post_comment_like_count: Annotated[int, Field(title="Post")]
    user_is_ignored: Annotated[bool, Field(title="User")]
    post_comment_is_published: Annotated[bool, Field(title="Post")]
    post_comment_is_deleted: Annotated[bool, Field(title="Post")]
    post_comment_update_date: Annotated[int, Field(title="Post")]
    links: Annotated[Links7, Field(title="Links")]
    permissions: Annotated[Permissions6, Field(title="Permissions")]


class Links8(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    permalink: Annotated[str, Field(title="Permalink")]
    detail: Annotated[str, Field(title="Detail")]
    timeline: Annotated[str, Field(title="Timeline")]
    timeline_user: Annotated[str, Field(title="Timeline")]
    poster: Annotated[str, Field(title="Poster")]
    likes: Annotated[str, Field(title="Likes")]
    comments: Annotated[str, Field(title="Comments")]
    report: Annotated[str, Field(title="Report")]
    poster_avatar: Annotated[str, Field(title="Poster")]


class Permissions8(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    view: Annotated[bool, Field(title="View")]
    edit: Annotated[bool, Field(title="Edit")]
    delete: Annotated[bool, Field(title="Delete")]
    like: Annotated[bool, Field(title="Like")]
    comment: Annotated[bool, Field(title="Comment")]
    report: Annotated[bool, Field(title="Report")]
    stick: Annotated[bool, Field(title="Stick")]


class RespProfilePostModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    profile_post_id: Annotated[int, Field(title="Profile")]
    timeline_user_id: Annotated[int, Field(title="Timeline")]
    poster_user_id: Annotated[int, Field(title="Poster")]
    poster_username: Annotated[str, Field(title="Poster")]
    poster_username_html: Annotated[str, Field(title="Poster")]
    post_create_date: Annotated[int, Field(title="Post")]
    post_body: Annotated[str, Field(title="Post")]
    post_body_html: Annotated[str, Field(title="Post")]
    post_body_plain_text: Annotated[str, Field(title="Post")]
    post_like_count: Annotated[int, Field(title="Post")]
    post_comment_count: Annotated[int, Field(title="Post")]
    post_comments_is_disabled: Annotated[int, Field(title="Post")]
    timeline_username: Annotated[str, Field(title="Timeline")]
    user_is_ignored: Annotated[bool, Field(title="User")]
    post_is_published: Annotated[bool, Field(title="Post")]
    post_is_deleted: Annotated[bool, Field(title="Post")]
    post_is_liked: Annotated[bool, Field(title="Post")]
    post_is_sticked: Annotated[bool, Field(title="Post")]
    links: Annotated[Links8, Field(title="Links")]
    permissions: Annotated[Permissions8, Field(title="Permissions")]
    timeline_user: RespUserModel


class Links9(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    detail: Annotated[str, Field(title="Detail")]
    profile_post: Annotated[str, Field(title="Profile")]
    timeline: Annotated[str, Field(title="Timeline")]
    timeline_user: Annotated[str, Field(title="Timeline")]
    poster: Annotated[str, Field(title="Poster")]
    poster_avatar: Annotated[str, Field(title="Poster")]


class Permissions9(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    view: Annotated[bool, Field(title="View")]
    delete: Annotated[bool, Field(title="Delete")]


class RespProfilePostCommentModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    comment_id: Annotated[int, Field(title="Comment")]
    profile_post_id: Annotated[int, Field(title="Profile")]
    comment_user_id: Annotated[int, Field(title="Comment")]
    comment_username: Annotated[str, Field(title="Comment")]
    comment_username_html: Annotated[str, Field(title="Comment")]
    comment_create_date: Annotated[int, Field(title="Comment")]
    comment_body: Annotated[str, Field(title="Comment")]
    comment_body_html: Annotated[str, Field(title="Comment")]
    comment_body_plain_text: Annotated[str, Field(title="Comment")]
    user_is_ignored: Annotated[bool, Field(title="User")]
    timeline_user_id: Annotated[int, Field(title="Timeline")]
    links: Annotated[Links9, Field(title="Links")]
    permissions: Annotated[Permissions9, Field(title="Permissions")]


class Permissions10(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    view: Annotated[bool, Field(title="View")]
    reply: Annotated[bool, Field(title="Reply")]
    invite: Annotated[bool, Field(title="Invite")]
    manage_invite_links: Annotated[bool, Field(title="Manage")]
    kick: Annotated[bool, Field(title="Kick")]
    upload_avatar: Annotated[bool, Field(title="Upload")]
    edit_own_post: Annotated[bool, Field(alias="editOwnPost", title="Edit Own Post")]
    sticky_messages: Annotated[bool, Field(alias="stickyMessages", title="Sticky Messages")]


class Recipient(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    user_id: Annotated[int, Field(title="User")]
    username: Annotated[str, Field(title="Username")]
    username_html: Annotated[str, Field(title="Username")]
    last_activity: Annotated[int, Field(title="Last")]
    is_online: Annotated[bool, Field(title="Is")]
    contacts_changed: Annotated[bool, Field(title="Contacts")]
    avatar: Annotated[str, Field(title="Avatar")]


class Links10(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    permalink: Annotated[str, Field(title="Permalink")]
    detail: Annotated[str, Field(title="Detail")]
    messages: Annotated[str, Field(title="Messages")]
    avatar: Annotated[str, Field(title="Avatar")]


class RespConversationModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    conversation_id: Annotated[int, Field(title="Conversation")]
    conversation_title: Annotated[str, Field(title="Conversation")]
    creator_user_id: Annotated[int, Field(title="Creator")]
    creator_username: Annotated[str, Field(title="Creator")]
    creator_username_html: Annotated[str, Field(title="Creator")]
    conversation_create_date: Annotated[int, Field(title="Conversation")]
    conversation_update_date: Annotated[int, Field(title="Conversation")]
    conversation_last_read_date: Annotated[int, Field(title="Conversation")]
    conversation_online_count: Annotated[int, Field(title="Conversation")]
    is_starred: Annotated[int, Field(title="Is")]
    is_group: Annotated[int, Field(title="Is")]
    is_unread: Annotated[int, Field(title="Is")]
    alerts: Annotated[int, Field(title="Alerts")]
    permissions: Annotated[Permissions10, Field(title="Permissions")]
    conversation_message_count: Annotated[int, Field(title="Conversation")]
    conversation_is_new: Annotated[bool, Field(title="Conversation")]
    creator_is_ignored: Annotated[bool, Field(title="Creator")]
    conversation_is_open: Annotated[bool, Field(title="Conversation")]
    conversation_is_deleted: Annotated[bool, Field(title="Conversation")]
    recipient: Annotated[Recipient, Field(title="Recipient")]
    recipients: Annotated[list[Recipient], Field(title="Recipients")]
    links: Annotated[Links10, Field(title="Links")]


class Links11(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    detail: Annotated[str, Field(title="Detail")]
    conversation: Annotated[str, Field(title="Conversation")]
    creator: Annotated[str, Field(title="Creator")]
    creator_avatar: Annotated[str, Field(title="Creator")]


class Permissions11(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    view: Annotated[bool, Field(title="View")]
    edit: Annotated[bool, Field(title="Edit")]
    delete: Annotated[bool, Field(title="Delete")]
    stick_unstick: Annotated[bool, Field(alias="stick-unstick", title="Stick")]


class RespConversationMessageModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    message_id: Annotated[int, Field(title="Message")]
    conversation_id: Annotated[int, Field(title="Conversation")]
    creator_user_id: Annotated[int, Field(title="Creator")]
    creator_username: Annotated[str, Field(title="Creator")]
    creator_username_html: Annotated[str, Field(title="Creator")]
    message_create_date: Annotated[int, Field(title="Message")]
    message_is_unread: Annotated[int, Field(title="Message")]
    message_need_translate: Annotated[bool, Field(title="Message")]
    message_is_system: Annotated[bool, Field(title="Message")]
    message_edit_date: Annotated[int, Field(title="Message")]
    message_body: Annotated[str, Field(title="Message")]
    message_body_html: Annotated[str, Field(title="Message")]
    message_body_plain_text: Annotated[str, Field(title="Message")]
    user_is_ignored: Annotated[bool, Field(title="User")]
    links: Annotated[Links11, Field(title="Links")]
    permissions: Annotated[Permissions11, Field(title="Permissions")]


class RespSystemInfo(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    visitor_id: int
    time: int
