# generated by datamodel-codegen:
#   filename:  market.json
#   timestamp: 2026-03-14T17:18:29+00:00

from __future__ import annotations

from enum import IntEnum, StrEnum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class DiscountModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    category_id: Annotated[int, Field(title="Category")]
    discount_id: Annotated[int, Field(title="Discount")]
    discount_percent: Annotated[int, Field(title="Discount")]
    discount_user_id: Annotated[int, Field(title="Discount")]
    max_price: Annotated[int, Field(title="Max")]
    min_price: Annotated[int, Field(title="Min")]
    user_id: Annotated[int, Field(title="User")]


class CategoryIDModel(IntEnum):
    integer_1 = 1
    integer_3 = 3
    integer_4 = 4
    integer_5 = 5
    integer_6 = 6
    integer_7 = 7
    integer_8 = 8
    integer_9 = 9
    integer_10 = 10
    integer_11 = 11
    integer_12 = 12
    integer_13 = 13
    integer_14 = 14
    integer_15 = 15
    integer_16 = 16
    integer_17 = 17
    integer_18 = 18
    integer_19 = 19
    integer_20 = 20
    integer_22 = 22
    integer_24 = 24
    integer_28 = 28
    integer_30 = 30
    integer_31 = 31


class Balance(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    balance: Annotated[str, Field(title="Balance")]
    balance_id: Annotated[int, Field(title="Balance")]
    converted_balance: Annotated[float, Field(alias="convertedBalance", title="Converted Balance")]
    custom_title: Annotated[Any, Field(title="Custom")]
    full_title: Annotated[str, Field(alias="fullTitle", title="Full Title")]
    merchant_id: Annotated[int, Field(title="Merchant")]
    title: Annotated[str, Field(title="Title")]
    type: Annotated[str, Field(title="Type")]
    user_id: Annotated[int, Field(title="User")]


class CustomFields(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_4: Annotated[str, Field(alias="_4", title="")]
    allow_self_unban: Annotated[list[Any], Field(alias="allowSelfUnban", title="Allow Self Unban")]
    ban_reason: Annotated[str, Field(title="Ban")]
    discord: Annotated[str, Field(title="Discord")]
    github: Annotated[str, Field(title="Github")]
    jabber: Annotated[str, Field(title="Jabber")]
    lzt_award_user_trophy: Annotated[str, Field(alias="lztAwardUserTrophy", title="Lzt Award User Trophy")]
    lzt_likes_increasing: Annotated[str, Field(alias="lztLikesIncreasing", title="Lzt Likes Increasing")]
    lzt_likes_zeroing: Annotated[str, Field(alias="lztLikesZeroing", title="Lzt Likes Zeroing")]
    lzt_sympathy_increasing: Annotated[str, Field(alias="lztSympathyIncreasing", title="Lzt Sympathy Increasing")]
    lzt_sympathy_zeroing: Annotated[str, Field(alias="lztSympathyZeroing", title="Lzt Sympathy Zeroing")]
    lzt_unban_amount: Annotated[str, Field(alias="lztUnbanAmount", title="Lzt Unban Amount")]
    maecenas_value: Annotated[str, Field(alias="maecenasValue", title="Maecenas Value")]
    scam_url: Annotated[str, Field(alias="scamURL", title="Scam Url")]
    steam: Annotated[str, Field(title="Steam")]
    telegram: Annotated[str, Field(title="Telegram")]
    vk: Annotated[str, Field(title="Vk")]
    favorite_porn: Annotated[str, Field(alias="favoritePorn", title="Favorite Porn")]
    favorite_vape: Annotated[str, Field(alias="favoriteVape", title="Favorite Vape")]
    favorite_anime: Annotated[str, Field(alias="favoriteAnime", title="Favorite Anime")]
    matrix: Annotated[str, Field(title="Matrix")]


class Dob(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    year: Annotated[int, Field(title="Year")]
    month: Annotated[int, Field(title="Month")]
    day: Annotated[int, Field(title="Day")]


class Field12345(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    positive: Annotated[int, Field(title="Positive")]
    negative: Annotated[int, Field(title="Negative")]


class FeedbackData(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_12345: Annotated[Field12345, Field(alias="12345", title="")]


class DomainZone(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    domain: Annotated[str, Field(title="Domain")]
    imap_server: Annotated[str, Field(title="Imap")]
    port: Annotated[int, Field(title="Port")]
    secure: Annotated[bool, Field(title="Secure")]


class ImapData(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    domain_zone: Annotated[DomainZone, Field(alias="domain.zone")]


class PublicTag(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    background_color: Annotated[str, Field(title="Background")]
    tag_id: Annotated[int, Field(title="Tag")]
    title: Annotated[str, Field(title="Title")]


class Avatars(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    l: Annotated[str, Field(title="L")]
    m: Annotated[str, Field(title="M")]
    s: Annotated[str, Field(title="S")]


class Backgrounds(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    l: Annotated[str, Field(title="L")]
    m: Annotated[str, Field(title="M")]


class Rendered(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    username: Annotated[str, Field(title="Username")]
    avatars: Annotated[Avatars, Field(title="Avatars")]
    backgrounds: Annotated[Backgrounds, Field(title="Backgrounds")]
    link: Annotated[str, Field(title="Link")]


class RestoreData(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_12345: Annotated[int, Field(alias="12345", title="")]


class Tag(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    tag_id: Annotated[int, Field(title="Tag")]
    title: Annotated[str, Field(title="Title")]
    is_default: Annotated[bool, Field(alias="isDefault", title="Is Default")]
    for_owned_accounts_only: Annotated[bool, Field(alias="forOwnedAccountsOnly", title="For Owned Accounts Only")]
    bc: Annotated[str, Field(title="Bc")]


class TelegramClient(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    telegram_api_id: Annotated[str, Field(title="Telegram")]
    telegram_api_hash: Annotated[str, Field(title="Telegram")]
    telegram_device_model: Annotated[str, Field(title="Telegram")]
    telegram_system_version: Annotated[str, Field(title="Telegram")]
    telegram_app_version: Annotated[str, Field(title="Telegram")]
    telegram_system_lang_code: Annotated[str, Field(title="Telegram")]
    telegram_lang_code: Annotated[str, Field(title="Telegram")]
    telegram_lang_pack: Annotated[str, Field(title="Telegram")]


class UserModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    active_items_count: Annotated[int, Field(title="Active")]
    activity_visible: Annotated[bool, Field(title="Activity")]
    age: Annotated[int, Field(title="Age")]
    balance: Annotated[str, Field(title="Balance")]
    balances: Annotated[list[Balance], Field(title="Balances")]
    bump_item_period: Annotated[int, Field(title="Bump")]
    can_edit: Annotated[bool, Field(title="Can")]
    can_follow: Annotated[bool, Field(title="Can")]
    can_ignore: Annotated[bool, Field(title="Can")]
    can_post_profile: Annotated[bool, Field(title="Can")]
    can_view_profile: Annotated[bool, Field(title="Can")]
    can_view_profile_posts: Annotated[bool, Field(title="Can")]
    can_warn: Annotated[bool, Field(title="Can")]
    contest_count: Annotated[int, Field(title="Contest")]
    conv_welcome_message: Annotated[str, Field(title="Conv")]
    converted_balance: Annotated[int, Field(alias="convertedBalance", title="Converted Balance")]
    converted_deposit: Annotated[int, Field(alias="convertedDeposit", title="Converted Deposit")]
    converted_hold: Annotated[int, Field(alias="convertedHold", title="Converted Hold")]
    currency: Annotated[str, Field(title="Currency")]
    currency_phrase: Annotated[str, Field(alias="currencyPhrase", title="Currency Phrase")]
    custom_account_download_format: Annotated[str, Field(title="Custom")]
    custom_fields: Annotated[CustomFields, Field(title="Custom")]
    custom_title: Annotated[str, Field(title="Custom")]
    deposit: Annotated[int, Field(title="Deposit")]
    dob: Annotated[Dob, Field(title="Dob")]
    feedback_data: Annotated[FeedbackData, Field(title="Feedback")]
    hold: Annotated[str, Field(title="Hold")]
    homepage: Annotated[str, Field(title="Homepage")]
    imap_data: Annotated[ImapData, Field(title="Imap")]
    is_admin: Annotated[bool, Field(title="Is")]
    is_banned: Annotated[bool, Field(title="Is")]
    is_followed: Annotated[bool, Field(title="Is")]
    is_ignored: Annotated[bool, Field(title="Is")]
    is_moderator: Annotated[bool, Field(title="Is")]
    is_staff: Annotated[bool, Field(title="Is")]
    is_super_admin: Annotated[bool, Field(title="Is")]
    joined_date: Annotated[int, Field(title="Joined")]
    last_activity: Annotated[int, Field(title="Last")]
    like2_count: Annotated[int, Field(title="Like")]
    like_count: Annotated[int, Field(title="Like")]
    location: Annotated[str, Field(title="Location")]
    market_custom_title: Annotated[str, Field(title="Market")]
    max_discount_percent: Annotated[int, Field(title="Max")]
    message_count: Annotated[int, Field(title="Message")]
    paid_mail_left: Annotated[int, Field(title="Paid")]
    public_tags: Annotated[list[PublicTag], Field(title="Public")]
    register_date: Annotated[int, Field(title="Register")]
    rendered: Annotated[Rendered, Field(title="Rendered")]
    restore_count: Annotated[int, Field(title="Restore")]
    restore_data: Annotated[RestoreData, Field(title="Restore")]
    short_link: Annotated[str, Field(title="Short")]
    sold_items_count: Annotated[int, Field(title="Sold")]
    tags: Annotated[list[Tag], Field(title="Tags")]
    telegram_client: Annotated[TelegramClient, Field(title="Telegram")]
    trophy_points: Annotated[int, Field(title="Trophy")]
    user_allow_ask_discount: Annotated[bool, Field(title="User")]
    user_id: Annotated[int, Field(title="User")]
    user_title: Annotated[str, Field(title="User")]
    username: Annotated[str, Field(title="Username")]
    view_url: Annotated[str, Field(title="View")]
    visible: Annotated[bool, Field(title="Visible")]
    warning_points: Annotated[int, Field(title="Warning")]


class BalanceModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    balance: Annotated[str, Field(title="Balance")]
    balance_id: Annotated[int, Field(title="Balance")]
    custom_title: Annotated[Any, Field(title="Custom")]
    full_title: Annotated[str, Field(alias="fullTitle", title="Full Title")]
    merchant_id: Annotated[int, Field(title="Merchant")]
    title: Annotated[str, Field(title="Title")]
    type: Annotated[str, Field(title="Type")]
    user_id: Annotated[int, Field(title="User")]


class Service(StrEnum):
    adguard_vpn = "AdguardVPN"
    piavpn = "PIAVPN"
    cyberghost_vpn = "cyberghostVPN"
    hotspot_shield_vpn = "hotspotShieldVPN"
    mullvad_vpn = "mullvadVPN"
    pure_vpn = "pureVPN"
    tunnelbear_vpn = "tunnelbearVPN"
    ultra_vpn = "ultraVPN"
    vanish_vpn = "vanishVPN"
    vypr_vpn = "vyprVPN"
    windscribe_vpn = "windscribeVPN"
    planet_vpn = "planetVPN"
    start = "start"
    ivi = "ivi"
    telegram = "telegram"
    discord = "discord"
    discord_trial = "discord_trial"


class System(StrEnum):
    laser = "laser"
    scroll = "scroll"
    magic = "magic"


class ExtraModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    proxy: Annotated[
        str | None,
        Field(
            description="Proxy line format ip:port:user:pass (prioritize over proxy_id parameter).",
            title="Proxy",
        ),
    ] = None
    close_item: Annotated[
        bool | None,
        Field(
            description="If set, the item will be closed **item_state = closed**.",
            title="Close Item",
        ),
    ] = None
    region: Annotated[
        str | None,
        Field(
            description="Region. Required if you want to upload WoT account. Optional if you want to upload miHoYo or Riot account.",
            title="Region",
        ),
    ] = None
    service: Annotated[
        Service | None,
        Field(
            description="Service. Required if you want to upload VPN, Cinema account or gift.",
            title="Service",
        ),
    ] = None
    system: Annotated[
        System | None,
        Field(
            description="Supercell system. Required if you want to upload Supercell account.",
            title="System",
        ),
    ] = None
    confirmation_code: Annotated[
        str | None,
        Field(
            alias="confirmationCode",
            description="Code from email (in case of problems). Optional if you want to upload Supercell account.",
            title="Confirmaton Code",
        ),
    ] = None
    cookies: Annotated[
        str | None,
        Field(
            description="Cookies. Required if you want to upload Fortnite, Epic Games, Social Club, Instagram or TikTok account.",
            title="Cookies",
        ),
    ] = None
    login_without_cookies: Annotated[
        bool | None,
        Field(
            description="Login without cookies. Optional if you want to upload Instagram account.",
            title="Login Without Cookies",
        ),
    ] = None
    cookie_login: Annotated[
        bool | None,
        Field(
            description="Cookie login. Optional. Used only if you want to upload TikTok account.",
            title="Cookie login",
        ),
    ] = None
    mfa_file: Annotated[
        str | None,
        Field(
            description="Steam mafile. Optional. Used only if you want to upload Steam account.",
            title="Mfa File",
        ),
    ] = None
    dota2_mmr: Annotated[
        int | None,
        Field(
            description="Dota 2 MMR. Optional. Used only if you want to upload Steam account.",
            title="Dota 2 MMR",
        ),
    ] = None
    ea_games: Annotated[
        bool | None,
        Field(
            description="EA Games. Optional. Used only if you want to upload Steam account.",
            title="EA Games",
        ),
    ] = None
    uplay_games: Annotated[
        bool | None,
        Field(
            description="Uplay Games. Optional. Used only if you want to upload Steam account.",
            title="Uplay Games",
        ),
    ] = None
    the_quarry: Annotated[
        bool | None,
        Field(
            description="The quarry. Optional. Used only if you want to upload Steam account.",
            title="The Quarry",
        ),
    ] = None
    warframe: Annotated[
        bool | None,
        Field(
            description="Warframe. Optional. Used only if you want to upload Steam account.",
            title="Warframe",
        ),
    ] = None
    ark: Annotated[
        bool | None,
        Field(
            description="Ark. Optional. Used only if you want to upload Steam account.",
            title="Ark",
        ),
    ] = None
    ark_ascended: Annotated[
        bool | None,
        Field(
            description="Ark Ascended. Optional. Used only if you want to upload Steam account.",
            title="Ark Ascended",
        ),
    ] = None
    genshin_currency: Annotated[
        int | None,
        Field(
            description="Genshin Impact Primogems count. Optional. Used only if you want to upload miHoYo account.",
            title="Ark Ascended",
        ),
    ] = None
    honkai_currency: Annotated[
        int | None,
        Field(
            description="Honkai Star Rail Stellar Jade count. Optional. Used only if you want to upload miHoYo account.",
            title="Stellar Jade",
        ),
    ] = None
    zenless_currency: Annotated[
        int | None,
        Field(
            description="Zenless Zone Zero Polychrome count. Optional. Used only if you want to upload miHoYo account.",
            title="Polychrome",
        ),
    ] = None
    password: Annotated[
        str | None,
        Field(
            description="Telegram 2FA Password. Optional. Used only if you want to upload Telegram account.",
            title="Telegram client",
        ),
    ] = None
    telegram_client: Annotated[
        str | None,
        Field(
            alias="telegramClient",
            description="Telegram client. Optional. Used only if you want to upload Telegram account.",
            examples=[
                '{"telegram_api_id": 0, "telegram_api_hash": "string", "telegram_device_model": "string", "telegram_system_version": "string", "telegram_app_version": "string", "telegram_lang_pack": "string", "telegram_lang_code": "string", "telegram_system_lang_code": string}'
            ],
            title="Telegram client",
        ),
    ] = None
    telegram_json: Annotated[
        str | None,
        Field(
            alias="telegramJson",
            description="Contents of session.json file. Optional. Used only if you want to upload Telegram account.",
            examples=[
                '{"session_file":"string","phone":"string","user_id":"string","app_id":0,"app_hash":"string","sdk":"string","app_version":"string","device":"string","device_token":"string","device_token_secret":"string","device_secret":"string","signature":"string","certificate":"string","safetynet":null,"perf_cat":null,"tz_offset":null,"register_time":0,"last_check_time":0,"avatar":null,"first_name":"string","last_name":"string","username":"string","sex":null,"spam":"string","premium":null,"lang_code":"string","system_lang_code":"string","lang_pack":"string","twoFA":"string","proxy":"string","ipv6":null,"module":"string","program":"string","time":"string"}'
            ],
            title="Telegram Json",
        ),
    ] = None
    check_channels: Annotated[
        bool | None,
        Field(
            alias="checkChannels",
            description="Check channels. Optional. Used only if you want to upload Telegram account.",
            title="Check Channels",
        ),
    ] = None
    check_spam: Annotated[
        bool | None,
        Field(
            alias="checkSpam",
            description="Check spam. Optional. Used only if you want to upload Telegram account.",
            title="Check Spam",
        ),
    ] = None
    check_hypixel_ban: Annotated[
        bool | None,
        Field(
            alias="checkHypixelBan",
            description="Check ban on Hypixel. Optional. Used only if you want to upload Minecraft account.",
            title="Check ban on Hypixel",
        ),
    ] = None


class CodeData(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: Annotated[str, Field(title="Code")]
    date: Annotated[int, Field(title="Date")]
    text_plain: Annotated[str, Field(alias="textPlain", title="Textplain")]


class CurrencyModel(StrEnum):
    rub = "rub"
    uah = "uah"
    kzt = "kzt"
    byn = "byn"
    usd = "usd"
    eur = "eur"
    gbp = "gbp"
    cny = "cny"
    try_ = "try"
    jpy = "jpy"
    brl = "brl"


class DatePeriodModel(StrEnum):
    day = "day"
    month = "month"
    year = "year"


class YesNoNoMatterScheme(StrEnum):
    yes = "yes"
    no = "no"
    nomatter = "nomatter"


class BumpSettings(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    can_bump_item: Annotated[bool | None, Field(alias="canBumpItem")] = False
    can_bump_item_globally: Annotated[bool | None, Field(alias="canBumpItemGlobally")] = False
    short_error_phrase: Annotated[str | None, Field(alias="shortErrorPhrase")] = None
    error_phrase: Annotated[str | None, Field(alias="errorPhrase")] = None


class Seller(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    user_id: int | None = 0
    sold_items_count: int | None = 0
    active_item_count: int | None = 0
    restore_data: str | None = "string"
    username: str | None = "string"
    avatar_date: int | None = 0
    is_banned: int | None = 0
    display_style_group_id: int | None = 0
    restore_percents: int | None = 0


class ItemFromListModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    item_id: int | None = 0
    item_state: str | None = "active"
    category_id: int | None = 0
    published_date: int | None = 0
    title: str | None = "Title"
    description: str | None = "Description"
    price: int | None = 0
    update_stat_date: int | None = 0
    refreshed_date: int | None = 0
    view_count: int | None = 0
    is_sticky: int | None = 0
    item_origin: str | None = "string"
    extended_guarantee: int | None = 0
    nsb: int | None = 0
    allow_ask_discount: int | None = 0
    title_en: str | None = "Title EN"
    description_en: str | None = "Description EN"
    item_domain: str | None = "string"
    resale_item_origin: str | None = "string"
    is_ignored: Annotated[int | None, Field(alias="isIgnored")] = 0
    guarantee: bool | None = None
    can_view_login_data: Annotated[bool | None, Field(alias="canViewLoginData")] = False
    can_update_item_stats: Annotated[bool | None, Field(alias="canUpdateItemStats")] = False
    can_view_email_login_data: Annotated[bool | None, Field(alias="canViewEmailLoginData")] = False
    show_get_email_code_button: Annotated[bool | None, Field(alias="showGetEmailCodeButton")] = False
    can_open_item: Annotated[bool | None, Field(alias="canOpenItem")] = False
    can_close_item: Annotated[bool | None, Field(alias="canCloseItem")] = False
    can_edit_item: Annotated[bool | None, Field(alias="canEditItem")] = False
    can_delete_item: Annotated[bool | None, Field(alias="canDeleteItem")] = False
    can_stick_item: Annotated[bool | None, Field(alias="canStickItem")] = False
    can_unstick_item: Annotated[bool | None, Field(alias="canUnstickItem")] = False
    bump_settings: Annotated[BumpSettings | None, Field(alias="bumpSettings")] = None
    can_bump_item: Annotated[bool | None, Field(alias="canBumpItem")] = False
    can_buy_item: Annotated[bool | None, Field(alias="canBuyItem")] = False
    rub_price: int | None = 0
    price_currency: str | None = "rub"
    can_validate_account: Annotated[bool | None, Field(alias="canValidateAccount")] = False
    can_resell_item_after_purchase: Annotated[bool | None, Field(alias="canResellItemAfterPurchase")] = False
    can_view_account_link: Annotated[bool | None, Field(alias="canViewAccountLink")] = False
    item_origin_phrase: Annotated[str | None, Field(alias="itemOriginPhrase")] = "string"
    tags: list[str] | None = None
    note_text: str | None = None
    description_html: str | None = "Description HTML"
    description_html_en: str | None = "Description HTML EN"
    seller: Seller | None = None


class Guarantee(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    duration: Annotated[int, Field(title="Duration")]
    class_: Annotated[str, Field(alias="class", title="Class")]
    duration_phrase: Annotated[str, Field(alias="durationPhrase", title="Duration Phrase")]
    end_date: Annotated[int, Field(alias="endDate", title="End Date")]
    active: Annotated[bool, Field(title="Active")]
    cancelled: Annotated[bool, Field(title="Cancelled")]
    remaining_time: Annotated[int, Field(alias="remainingTime", title="Remaining Time")]
    remaining_time_phrase: Annotated[str, Field(alias="remainingTimePhrase", title="Remaining Time Phrase")]
    cancelled_reason: Annotated[str, Field(alias="cancelledReason", title="Cancelled Reason")]
    cancelled_reason_phrase: Annotated[str, Field(alias="cancelledReasonPhrase", title="Cancelled Reason Phrase")]


class LoginData(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    raw: Annotated[str, Field(title="Raw")]
    encoded_raw: Annotated[str, Field(alias="encodedRaw", title="Encoded Raw")]
    login: Annotated[str, Field(title="Login")]
    password: Annotated[str, Field(title="Password")]
    encoded_password: Annotated[str, Field(alias="encodedPassword", title="Encoded Password")]
    old_password: Annotated[str, Field(alias="oldPassword", title="Old Password")]
    encoded_old_password: Annotated[Any, Field(alias="encodedOldPassword", title="Encoded Old Password")]


class CopyFormatData(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    title_link: Annotated[str, Field(title="Title")]
    login_data: Annotated[str, Field(title="Login")]
    full: Annotated[str, Field(title="Full")]


class Buyer(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    user_id: Annotated[int, Field(title="User")]
    operation_date: Annotated[int, Field(title="Operation")]
    visitor_is_buyer: Annotated[bool, Field(alias="visitorIsBuyer", title="Visitor Is Buyer")]
    username: Annotated[str, Field(title="Username")]
    is_banned: Annotated[int, Field(title="Is")]
    display_style_group_id: Annotated[int, Field(title="Display")]
    display_icon_group_id: Annotated[int, Field(title="Display")]
    uniq_username_css: Annotated[str, Field(title="Uniq")]
    uniq_banner: Annotated[str, Field(title="Uniq")]
    user_group_id: Annotated[int, Field(title="User")]


class AccountLink(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    link: Annotated[str, Field(title="Link")]
    text: Annotated[str, Field(title="Text")]
    icon_class: Annotated[str, Field(alias="iconClass", title="Icon Class")]


class Field1234567890(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    tag_id: Annotated[int, Field(title="Tag")]
    title: Annotated[str, Field(title="Title")]
    is_default: Annotated[bool, Field(alias="isDefault", title="Is Default")]
    for_owned_accounts_only: Annotated[bool, Field(alias="forOwnedAccountsOnly", title="For Owned Accounts Only")]
    bc: Annotated[str, Field(title="Bc")]


class Tags(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_1234567890: Annotated[Field1234567890, Field(alias="1234567890", title="")]


class CustomFields1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_4: Annotated[str, Field(alias="_4", title="")]
    allow_self_unban: Annotated[list[Any], Field(alias="allowSelfUnban", title="Allow Self Unban")]
    ban_reason: Annotated[str, Field(title="Ban")]
    discord: Annotated[str, Field(title="Discord")]
    github: Annotated[str, Field(title="Github")]
    jabber: Annotated[str, Field(title="Jabber")]
    lzt_unban_amount: Annotated[str, Field(alias="lztUnbanAmount", title="Lzt Unban Amount")]
    steam: Annotated[str, Field(title="Steam")]
    telegram: Annotated[str, Field(title="Telegram")]
    vk: Annotated[str, Field(title="Vk")]


class ExtraPrice(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    currency: Annotated[str, Field(title="Currency")]
    price: Annotated[str, Field(title="Price")]
    price_value: Annotated[float, Field(alias="priceValue", title="Price Value")]


class BumpSettings1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    can_bump_item: Annotated[bool, Field(alias="canBumpItem", title="Can Bump Item")]
    can_bump_item_globally: Annotated[bool, Field(alias="canBumpItemGlobally", title="Can Bump Item Globally")]
    short_error_phrase: Annotated[Any, Field(alias="shortErrorPhrase", title="Short Error Phrase")]
    next_allowed_bump_date: Annotated[Any, Field(alias="nextAllowedBumpDate", title="Next Allowed Bump Date")]
    error_phrase: Annotated[Any, Field(alias="errorPhrase", title="Error Phrase")]


class Contacts(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ban_reason: Annotated[str, Field(title="Ban")]
    telegram: Annotated[str, Field(title="Telegram")]


class Seller1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    user_id: Annotated[int, Field(title="User")]
    username: Annotated[str, Field(title="Username")]
    avatar_date: Annotated[int, Field(title="Avatar")]
    is_banned: Annotated[int, Field(title="Is")]
    display_style_group_id: Annotated[int, Field(title="Display")]
    joined_date: Annotated[int, Field(title="Joined")]
    sold_items_count: Annotated[int, Field(title="Sold")]
    active_items_count: Annotated[int, Field(title="Active")]
    restore_data: Annotated[str, Field(title="Restore")]
    effective_last_activity: Annotated[int, Field(title="Effective")]
    restore_percents: Annotated[Any, Field(title="Restore")]
    is_online: Annotated[bool, Field(alias="isOnline", title="Is Online")]
    contacts: Annotated[Contacts, Field(title="Contacts")]


class ItemModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    item_id: Annotated[int, Field(title="Item")]
    item_state: Annotated[str, Field(title="Item")]
    category_id: Annotated[int, Field(title="Category")]
    published_date: Annotated[int, Field(title="Published")]
    title: Annotated[str, Field(title="Title")]
    description: Annotated[str, Field(title="Description")]
    price: Annotated[int, Field(title="Price")]
    update_stat_date: Annotated[int, Field(title="Update")]
    refreshed_date: Annotated[int, Field(title="Refreshed")]
    edit_date: Annotated[int, Field(title="Edit")]
    pending_deletion_date: Annotated[int, Field(title="Pending")]
    login: Annotated[str, Field(title="Login")]
    temp_email: Annotated[str, Field(title="Temp")]
    view_count: Annotated[int, Field(title="View")]
    is_sticky: Annotated[int, Field(title="Is")]
    information: Annotated[str, Field(title="Information")]
    item_origin: Annotated[str, Field(title="Item")]
    extended_guarantee: Annotated[int, Field(title="Extended")]
    nsb: Annotated[int, Field(title="Nsb")]
    allow_ask_discount: Annotated[int, Field(title="Allow")]
    title_en: Annotated[str, Field(title="Title")]
    description_en: Annotated[str, Field(title="Description")]
    information_en: Annotated[str, Field(title="Information")]
    email_type: Annotated[str, Field(title="Email")]
    email_provider: Annotated[str, Field(title="Email")]
    item_domain: Annotated[str, Field(title="Item")]
    resale_item_origin: Annotated[str, Field(title="Resale")]
    note_text: Annotated[str, Field(title="Note")]
    content_type: Annotated[Any, Field(title="Content")]
    content_id: Annotated[Any, Field(title="Content")]
    delete_date: Annotated[int, Field(title="Delete")]
    delete_user_id: Annotated[int, Field(title="Delete")]
    delete_username: Annotated[str, Field(title="Delete")]
    delete_reason: Annotated[str, Field(title="Delete")]
    user_allow_ask_discount: Annotated[int, Field(title="User")]
    max_discount_percent: Annotated[int, Field(title="Max")]
    market_custom_title: Annotated[str, Field(title="Market")]
    feedback_data: Annotated[str, Field(title="Feedback")]
    buyer_display_icon_group_id: Annotated[int, Field(title="Buyer")]
    buyer_uniq_banner: Annotated[str, Field(title="Buyer")]
    buyer_avatar_date: Annotated[int, Field(title="Buyer")]
    buyer_user_group_id: Annotated[int, Field(title="Buyer")]
    is_fave: Annotated[Any, Field(title="Is")]
    in_cart: Annotated[Any, Field(title="In")]
    cart_price: Annotated[Any, Field(title="Cart")]
    can_resell_item: Annotated[bool, Field(alias="canResellItem", title="Can Resell Item")]
    price_with_seller_fee: Annotated[float, Field(alias="priceWithSellerFee", title="Price With Seller Fee")]
    guarantee: Annotated[Guarantee, Field(title="Guarantee")]
    can_view_login_data: Annotated[bool, Field(alias="canViewLoginData", title="Can View Login Data")]
    can_update_item_stats: Annotated[bool, Field(alias="canUpdateItemStats", title="Can Update Item Stats")]
    can_report_item: Annotated[bool, Field(alias="canReportItem", title="Can Report Item")]
    can_view_item_views: Annotated[bool, Field(alias="canViewItemViews", title="Can View Item Views")]
    login_data: Annotated[LoginData, Field(alias="loginData", title="Login Data")]
    can_view_email_login_data: Annotated[bool, Field(alias="canViewEmailLoginData", title="Can View Email Login Data")]
    copy_format_data: Annotated[CopyFormatData, Field(alias="copyFormatData", title="Copy Format Data")]
    show_get_email_code_button: Annotated[
        bool, Field(alias="showGetEmailCodeButton", title="Show Get Email Code Button")
    ]
    get_email_code_display_login: Annotated[
        Any,
        Field(alias="getEmailCodeDisplayLogin", title="Get Email Code Display Login"),
    ]
    buyer: Annotated[Buyer, Field(title="Buyer")]
    is_personal_account: Annotated[bool, Field(alias="isPersonalAccount", title="Is Personal Account")]
    rub_price: Annotated[int, Field(title="Rub")]
    price_currency: Annotated[str, Field(title="Price")]
    price_with_seller_fee_label: Annotated[
        str, Field(alias="priceWithSellerFeeLabel", title="Price With Seller Fee Label")
    ]
    can_validate_account: Annotated[bool, Field(alias="canValidateAccount", title="Can Validate Account")]
    can_resell_item_after_purchase: Annotated[
        bool,
        Field(alias="canResellItemAfterPurchase", title="Can Resell Item After Purchase"),
    ]
    is_small_exf: Annotated[bool, Field(alias="isSmallExf", title="Is Small Exf")]
    account_last_activity: Annotated[int, Field(title="Account")]
    can_view_account_link: Annotated[bool, Field(alias="canViewAccountLink", title="Can View Account Link")]
    account_links: Annotated[list[AccountLink], Field(alias="accountLinks", title="Account Links")]
    account_link: Annotated[str, Field(alias="accountLink", title="Account Link")]
    image_preview_links: Annotated[list[str], Field(alias="imagePreviewLinks", title="Image Preview Links")]
    can_change_password: Annotated[bool, Field(alias="canChangePassword", title="Can Change Password")]
    can_change_email_password: Annotated[bool, Field(alias="canChangeEmailPassword", title="Can Change Email Password")]
    unique_key_exists: Annotated[bool, Field(alias="uniqueKeyExists", title="Unique Key Exists")]
    item_origin_phrase: Annotated[str, Field(alias="itemOriginPhrase", title="Item Origin Phrase")]
    visitor_is_author: Annotated[bool, Field(alias="visitorIsAuthor", title="Visitor Is Author")]
    can_ask_discount: Annotated[bool, Field(alias="canAskDiscount", title="Can Ask Discount")]
    tags: Annotated[Tags, Field(title="Tags")]
    custom_fields: Annotated[CustomFields1, Field(alias="customFields", title="Custom Fields")]
    external_auth: Annotated[list[Any], Field(alias="externalAuth", title="External Auth")]
    is_trusted: Annotated[bool, Field(alias="isTrusted", title="Is Trusted")]
    is_birthday_today: Annotated[bool, Field(alias="isBirthdayToday", title="Is Birthday Today")]
    is_ignored: Annotated[bool, Field(alias="isIgnored", title="Is Ignored")]
    deposit: Annotated[int, Field(title="Deposit")]
    extra_prices: Annotated[list[ExtraPrice], Field(alias="extraPrices", title="Extra Prices")]
    can_view_account_login_and_temp_email: Annotated[
        bool,
        Field(
            alias="canViewAccountLoginAndTempEmail",
            title="Can View Account Login And Temp Email",
        ),
    ]
    bump_settings: Annotated[BumpSettings1, Field(alias="bumpSettings", title="Bump Settings")]
    can_check_guarantee: Annotated[bool, Field(alias="canCheckGuarantee", title="Can Check Guarantee")]
    can_share_item: Annotated[bool, Field(alias="canShareItem", title="Can Share Item")]
    can_check_ai_price: Annotated[bool, Field(alias="canCheckAiPrice", title="Can Check Ai Price")]
    ai_price: Annotated[int, Field(alias="aiPrice", title="Ai Price")]
    ai_price_check_date: Annotated[int, Field(alias="aiPriceCheckDate", title="Ai Price Check Date")]
    need_to_require_video_to_view_login_data: Annotated[
        bool,
        Field(
            alias="needToRequireVideoToViewLoginData",
            title="Need To Require Video To View Login Data",
        ),
    ]
    can_check_auto_buy_price: Annotated[bool, Field(alias="canCheckAutoBuyPrice", title="Can Check Auto Buy Price")]
    auto_buy_price: Annotated[int, Field(alias="autoBuyPrice", title="Auto Buy Price")]
    auto_buy_price_check_date: Annotated[int, Field(alias="autoBuyPriceCheckDate", title="Auto Buy Price Check Date")]
    description_html: Annotated[str, Field(alias="descriptionHtml", title="Description Html")]
    description_en_html: Annotated[str, Field(alias="descriptionEnHtml", title="Description En Html")]
    description_plain: Annotated[str, Field(alias="descriptionPlain", title="Description Plain")]
    description_en_plain: Annotated[str, Field(alias="descriptionEnPlain", title="Description En Plain")]
    seller: Annotated[Seller1, Field(title="Seller")]


class ItemIDModel(RootModel[int]):
    root: Annotated[int, Field(description="Item id.", title="Item ID")]


class InvoiceModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    additional_data: Annotated[str, Field(title="Additional")]
    amount: Annotated[int, Field(title="Amount")]
    comment: Annotated[str, Field(title="Comment")]
    expires_at: Annotated[int, Field(title="Expires")]
    invoice_date: Annotated[int, Field(title="Invoice")]
    invoice_id: Annotated[int, Field(title="Invoice")]
    is_test: Annotated[bool, Field(title="Is")]
    merchant_id: Annotated[int, Field(title="Merchant")]
    paid_date: Annotated[int, Field(title="Paid")]
    payer_user_id: Annotated[int, Field(title="Payer")]
    payment_id: Annotated[str, Field(title="Payment")]
    resend_attempts: Annotated[int, Field(title="Resend")]
    status: Annotated[str, Field(title="Status")]
    url: Annotated[str, Field(title="Url")]
    url_callback: Annotated[str, Field(title="Url")]
    url_success: Annotated[str, Field(title="Url")]
    user_id: Annotated[int, Field(title="User")]


class RespSystemInfo(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    visitor_id: int
    time: int
    log_id: int


class ConfirmationCodeModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    item: ItemModel
    code_data: Annotated[CodeData, Field(alias="codeData", title="CodeData")]


class ItemListModel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    items: list[ItemFromListModel]
    total_items: Annotated[int, Field(alias="totalItems", title="Total Items")]
    total_items_price: Annotated[Any, Field(alias="totalItemsPrice", title="Total Items Price")]
    has_next_page: Annotated[bool, Field(alias="hasNextPage", title="Has Next Page")]
    per_page: Annotated[int, Field(alias="perPage", title="Per Page")]
    page: Annotated[int, Field(title="Page")]
    search_url: Annotated[str, Field(alias="searchUrl", title="Search Url")]
    sticky_items: Annotated[list[ItemFromListModel], Field(alias="stickyItems")]
    system_info: RespSystemInfo
